(cl:defpackage my_custom_pkg-msg
  (:use )
  (:export
   "<COUNTINGACTION>"
   "COUNTINGACTION"
   "<COUNTINGACTIONFEEDBACK>"
   "COUNTINGACTIONFEEDBACK"
   "<COUNTINGACTIONGOAL>"
   "COUNTINGACTIONGOAL"
   "<COUNTINGACTIONRESULT>"
   "COUNTINGACTIONRESULT"
   "<COUNTINGFEEDBACK>"
   "COUNTINGFEEDBACK"
   "<COUNTINGGOAL>"
   "COUNTINGGOAL"
   "<COUNTINGRESULT>"
   "COUNTINGRESULT"
   "<MOTION>"
   "MOTION"
   "<PERSON>"
   "PERSON"
  ))

