; Auto-generated. Do not edit!


(cl:in-package my_custom_pkg-msg)


;//! \htmlinclude CountingGoal.msg.html

(cl:defclass <CountingGoal> (roslisp-msg-protocol:ros-message)
  ((max_number
    :reader max_number
    :initarg :max_number
    :type cl:integer
    :initform 0))
)

(cl:defclass CountingGoal (<CountingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_custom_pkg-msg:<CountingGoal> is deprecated: use my_custom_pkg-msg:CountingGoal instead.")))

(cl:ensure-generic-function 'max_number-val :lambda-list '(m))
(cl:defmethod max_number-val ((m <CountingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_custom_pkg-msg:max_number-val is deprecated.  Use my_custom_pkg-msg:max_number instead.")
  (max_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountingGoal>) ostream)
  "Serializes a message object of type '<CountingGoal>"
  (cl:let* ((signed (cl:slot-value msg 'max_number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountingGoal>) istream)
  "Deserializes a message object of type '<CountingGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'max_number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountingGoal>)))
  "Returns string type for a message object of type '<CountingGoal>"
  "my_custom_pkg/CountingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountingGoal)))
  "Returns string type for a message object of type 'CountingGoal"
  "my_custom_pkg/CountingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountingGoal>)))
  "Returns md5sum for a message object of type '<CountingGoal>"
  "f441ae3d585d128c715a0dcb45884935")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountingGoal)))
  "Returns md5sum for a message object of type 'CountingGoal"
  "f441ae3d585d128c715a0dcb45884935")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountingGoal>)))
  "Returns full string definition for message of type '<CountingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# CountingAction.action~%# Goal~%int32 max_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountingGoal)))
  "Returns full string definition for message of type 'CountingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# CountingAction.action~%# Goal~%int32 max_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountingGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CountingGoal
    (cl:cons ':max_number (max_number msg))
))
