; Auto-generated. Do not edit!


(cl:in-package my_custom_pkg-msg)


;//! \htmlinclude CountingFeedback.msg.html

(cl:defclass <CountingFeedback> (roslisp-msg-protocol:ros-message)
  ((current_numbers
    :reader current_numbers
    :initarg :current_numbers
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass CountingFeedback (<CountingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_custom_pkg-msg:<CountingFeedback> is deprecated: use my_custom_pkg-msg:CountingFeedback instead.")))

(cl:ensure-generic-function 'current_numbers-val :lambda-list '(m))
(cl:defmethod current_numbers-val ((m <CountingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_custom_pkg-msg:current_numbers-val is deprecated.  Use my_custom_pkg-msg:current_numbers instead.")
  (current_numbers m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountingFeedback>) ostream)
  "Serializes a message object of type '<CountingFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'current_numbers))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'current_numbers))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountingFeedback>) istream)
  "Deserializes a message object of type '<CountingFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'current_numbers) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'current_numbers)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountingFeedback>)))
  "Returns string type for a message object of type '<CountingFeedback>"
  "my_custom_pkg/CountingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountingFeedback)))
  "Returns string type for a message object of type 'CountingFeedback"
  "my_custom_pkg/CountingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountingFeedback>)))
  "Returns md5sum for a message object of type '<CountingFeedback>"
  "c50bc850a7b2d2f8b94b1e351e800efe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountingFeedback)))
  "Returns md5sum for a message object of type 'CountingFeedback"
  "c50bc850a7b2d2f8b94b1e351e800efe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountingFeedback>)))
  "Returns full string definition for message of type '<CountingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int32[] current_numbers~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountingFeedback)))
  "Returns full string definition for message of type 'CountingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int32[] current_numbers~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountingFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'current_numbers) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CountingFeedback
    (cl:cons ':current_numbers (current_numbers msg))
))
