// Auto-generated. Do not edit!

// (in-package my_custom_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountingFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_numbers = null;
    }
    else {
      if (initObj.hasOwnProperty('current_numbers')) {
        this.current_numbers = initObj.current_numbers
      }
      else {
        this.current_numbers = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountingFeedback
    // Serialize message field [current_numbers]
    bufferOffset = _arraySerializer.int32(obj.current_numbers, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountingFeedback
    let len;
    let data = new CountingFeedback(null);
    // Deserialize message field [current_numbers]
    data.current_numbers = _arrayDeserializer.int32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.current_numbers.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_custom_pkg/CountingFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c50bc850a7b2d2f8b94b1e351e800efe';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    int32[] current_numbers
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountingFeedback(null);
    if (msg.current_numbers !== undefined) {
      resolved.current_numbers = msg.current_numbers;
    }
    else {
      resolved.current_numbers = []
    }

    return resolved;
    }
};

module.exports = CountingFeedback;
