// Auto-generated. Do not edit!

// (in-package my_custom_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountingResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.final_numbers = null;
      this.result_message = null;
    }
    else {
      if (initObj.hasOwnProperty('final_numbers')) {
        this.final_numbers = initObj.final_numbers
      }
      else {
        this.final_numbers = [];
      }
      if (initObj.hasOwnProperty('result_message')) {
        this.result_message = initObj.result_message
      }
      else {
        this.result_message = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountingResult
    // Serialize message field [final_numbers]
    bufferOffset = _arraySerializer.int32(obj.final_numbers, buffer, bufferOffset, null);
    // Serialize message field [result_message]
    bufferOffset = _serializer.string(obj.result_message, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountingResult
    let len;
    let data = new CountingResult(null);
    // Deserialize message field [final_numbers]
    data.final_numbers = _arrayDeserializer.int32(buffer, bufferOffset, null)
    // Deserialize message field [result_message]
    data.result_message = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.final_numbers.length;
    length += _getByteLength(object.result_message);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_custom_pkg/CountingResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '943ce6579b0573eb104ddf192af3fcae';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    int32[] final_numbers
    string result_message
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountingResult(null);
    if (msg.final_numbers !== undefined) {
      resolved.final_numbers = msg.final_numbers;
    }
    else {
      resolved.final_numbers = []
    }

    if (msg.result_message !== undefined) {
      resolved.result_message = msg.result_message;
    }
    else {
      resolved.result_message = ''
    }

    return resolved;
    }
};

module.exports = CountingResult;
