// Auto-generated. Do not edit!

// (in-package my_custom_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountingGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.max_number = null;
    }
    else {
      if (initObj.hasOwnProperty('max_number')) {
        this.max_number = initObj.max_number
      }
      else {
        this.max_number = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountingGoal
    // Serialize message field [max_number]
    bufferOffset = _serializer.int32(obj.max_number, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountingGoal
    let len;
    let data = new CountingGoal(null);
    // Deserialize message field [max_number]
    data.max_number = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_custom_pkg/CountingGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f441ae3d585d128c715a0dcb45884935';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # CountingAction.action
    # Goal
    int32 max_number
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountingGoal(null);
    if (msg.max_number !== undefined) {
      resolved.max_number = msg.max_number;
    }
    else {
      resolved.max_number = 0
    }

    return resolved;
    }
};

module.exports = CountingGoal;
