// Generated by gencpp from file my_custom_pkg/CountingGoal.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_PKG_MESSAGE_COUNTINGGOAL_H
#define MY_CUSTOM_PKG_MESSAGE_COUNTINGGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_custom_pkg
{
template <class ContainerAllocator>
struct CountingGoal_
{
  typedef CountingGoal_<ContainerAllocator> Type;

  CountingGoal_()
    : max_number(0)  {
    }
  CountingGoal_(const ContainerAllocator& _alloc)
    : max_number(0)  {
  (void)_alloc;
    }



   typedef int32_t _max_number_type;
  _max_number_type max_number;





  typedef boost::shared_ptr< ::my_custom_pkg::CountingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_pkg::CountingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CountingGoal_

typedef ::my_custom_pkg::CountingGoal_<std::allocator<void> > CountingGoal;

typedef boost::shared_ptr< ::my_custom_pkg::CountingGoal > CountingGoalPtr;
typedef boost::shared_ptr< ::my_custom_pkg::CountingGoal const> CountingGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_pkg::CountingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_custom_pkg::CountingGoal_<ContainerAllocator1> & lhs, const ::my_custom_pkg::CountingGoal_<ContainerAllocator2> & rhs)
{
  return lhs.max_number == rhs.max_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_custom_pkg::CountingGoal_<ContainerAllocator1> & lhs, const ::my_custom_pkg::CountingGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_custom_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_pkg::CountingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_pkg::CountingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_pkg::CountingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f441ae3d585d128c715a0dcb45884935";
  }

  static const char* value(const ::my_custom_pkg::CountingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf441ae3d585d128cULL;
  static const uint64_t static_value2 = 0x715a0dcb45884935ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_pkg/CountingGoal";
  }

  static const char* value(const ::my_custom_pkg::CountingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# CountingAction.action\n"
"# Goal\n"
"int32 max_number\n"
;
  }

  static const char* value(const ::my_custom_pkg::CountingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_pkg::CountingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_pkg::CountingGoal_<ContainerAllocator>& v)
  {
    s << indent << "max_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_PKG_MESSAGE_COUNTINGGOAL_H
