// Generated by gencpp from file my_custom_pkg/CountingFeedback.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_PKG_MESSAGE_COUNTINGFEEDBACK_H
#define MY_CUSTOM_PKG_MESSAGE_COUNTINGFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_custom_pkg
{
template <class ContainerAllocator>
struct CountingFeedback_
{
  typedef CountingFeedback_<ContainerAllocator> Type;

  CountingFeedback_()
    : current_numbers()  {
    }
  CountingFeedback_(const ContainerAllocator& _alloc)
    : current_numbers(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _current_numbers_type;
  _current_numbers_type current_numbers;





  typedef boost::shared_ptr< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CountingFeedback_

typedef ::my_custom_pkg::CountingFeedback_<std::allocator<void> > CountingFeedback;

typedef boost::shared_ptr< ::my_custom_pkg::CountingFeedback > CountingFeedbackPtr;
typedef boost::shared_ptr< ::my_custom_pkg::CountingFeedback const> CountingFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_pkg::CountingFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_custom_pkg::CountingFeedback_<ContainerAllocator1> & lhs, const ::my_custom_pkg::CountingFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_numbers == rhs.current_numbers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_custom_pkg::CountingFeedback_<ContainerAllocator1> & lhs, const ::my_custom_pkg::CountingFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_custom_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c50bc850a7b2d2f8b94b1e351e800efe";
  }

  static const char* value(const ::my_custom_pkg::CountingFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc50bc850a7b2d2f8ULL;
  static const uint64_t static_value2 = 0xb94b1e351e800efeULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_pkg/CountingFeedback";
  }

  static const char* value(const ::my_custom_pkg::CountingFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"int32[] current_numbers\n"
;
  }

  static const char* value(const ::my_custom_pkg::CountingFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_numbers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountingFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_pkg::CountingFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_pkg::CountingFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_numbers[]" << std::endl;
    for (size_t i = 0; i < v.current_numbers.size(); ++i)
    {
      s << indent << "  current_numbers[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.current_numbers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_PKG_MESSAGE_COUNTINGFEEDBACK_H
