// Generated by gencpp from file my_custom_pkg/Motion.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_PKG_MESSAGE_MOTION_H
#define MY_CUSTOM_PKG_MESSAGE_MOTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_custom_pkg
{
template <class ContainerAllocator>
struct Motion_
{
  typedef Motion_<ContainerAllocator> Type;

  Motion_()
    : move_x(0)
    , move_y(0)  {
    }
  Motion_(const ContainerAllocator& _alloc)
    : move_x(0)
    , move_y(0)  {
  (void)_alloc;
    }



   typedef int32_t _move_x_type;
  _move_x_type move_x;

   typedef int32_t _move_y_type;
  _move_y_type move_y;





  typedef boost::shared_ptr< ::my_custom_pkg::Motion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_pkg::Motion_<ContainerAllocator> const> ConstPtr;

}; // struct Motion_

typedef ::my_custom_pkg::Motion_<std::allocator<void> > Motion;

typedef boost::shared_ptr< ::my_custom_pkg::Motion > MotionPtr;
typedef boost::shared_ptr< ::my_custom_pkg::Motion const> MotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_pkg::Motion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_pkg::Motion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_custom_pkg::Motion_<ContainerAllocator1> & lhs, const ::my_custom_pkg::Motion_<ContainerAllocator2> & rhs)
{
  return lhs.move_x == rhs.move_x &&
    lhs.move_y == rhs.move_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_custom_pkg::Motion_<ContainerAllocator1> & lhs, const ::my_custom_pkg::Motion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_custom_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_custom_pkg::Motion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_pkg::Motion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_pkg::Motion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_pkg::Motion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_pkg::Motion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_pkg::Motion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_pkg::Motion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4a87f7185f394984e658d3952988396";
  }

  static const char* value(const ::my_custom_pkg::Motion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4a87f7185f39498ULL;
  static const uint64_t static_value2 = 0x4e658d3952988396ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_pkg::Motion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_pkg/Motion";
  }

  static const char* value(const ::my_custom_pkg::Motion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_pkg::Motion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 move_x\n"
"int32 move_y\n"
;
  }

  static const char* value(const ::my_custom_pkg::Motion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_pkg::Motion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.move_x);
      stream.next(m.move_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_pkg::Motion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_pkg::Motion_<ContainerAllocator>& v)
  {
    s << indent << "move_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.move_x);
    s << indent << "move_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.move_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_PKG_MESSAGE_MOTION_H
